import React, { useState, useEffect } from 'react';
import { Text, ScrollView, TouchableOpacity, LayoutAnimation, BackHandler, View, TextInput } from 'react-native';
import Ionicons from 'react-native-vector-icons/Ionicons';
import Icon from 'react-native-vector-icons/FontAwesome';

// styles
import { UniversalContainerStyle as styles1 } from '../../styles/index';
import LinearGradient from 'react-native-linear-gradient';
import colors from '../../utils/colors';
import { FaqScreenStyle as styles, ActivityScreenStyle as styles2 } from '../../styles/index';

const FaqScreen = ({ navigation }) => {
  const [selectedQuestionIndex, setSelectedQuestionIndex] = useState(-1);

  const questions = [
    {
      question: 'What is Total Revenue?',
      answer: 'Total Revenue is the total amount of income generated by the business from sales or other sources, before any deductions or expenses are taken out.',
    },
    {
      question: 'What is Total Expense?',
      answer: 'Total Expense is the total amount of money spent by the business on all expenses, including salaries, rent, utilities, supplies, and any other costs.',
    },
    {
      question: 'What is Gross Profit?',
      answer: 'Gross Profit is the difference between Total Revenue and Total Cost of Sales. It represents the amount of money the business has left over after deducting the cost of goods sold.',
    },
    {
      question: 'What is Net Profit?',
      answer: 'Net Profit is the amount of money the business earns after all expenses and taxes have been deducted from Total Revenue.',
    },
    {
      question: 'What is Total Receivable?',
      answer: 'Total Receivable is the total amount of money owed to the business by its customers or clients.',
    },
    {
      question: 'What is Total Payable?',
      answer: 'Total Payable is the total amount of money the business owes to its suppliers, vendors, or creditors.',
    },
    {
      question: 'What is Payroll?',
      answer: 'Payroll is the amount of money the business pays to its employees for their work, including salaries, wages, and benefits.',
    },
    {
      question: 'What is RDP?',
      answer: 'Retention refers to the percentage of repeated products that a business is selling repeatedly',
    },
    {
      question: 'What is Inventory?',
      answer: 'Inventory refers to the total amount of goods or products the business has on hand at any given time, including raw materials, work-in-progress, and finished goods.',
    },
    {
      question: 'What is ARPU?',
      answer: 'ARPU stands for Average Revenue Per User, and is calculated by dividing Total Revenue by the total number of users or customers.',
    },
    {
      question: 'What is CAC?',
      answer: 'CAC stands for Customer Acquisition Cost, and is the total amount of money the business spends on marketing, advertising, and other efforts to acquire new customers.',
    },
    {
      question: 'What is AOV?',
      answer: 'AOV stands for Average Order Value, and is calculated by dividing Total Revenue by the total number of orders.',
    },
    {
      question: 'What is Cost of Sale?',
      answer: 'Cost of Sale refers to the total cost of producing or acquiring the goods or products sold by the business, including raw materials, labor, and overhead expenses.',
    },
    {
      question: 'What is EBITDA?',
      answer: 'EBITDA stands for Earnings Before Interest, Taxes, Depreciation, and Amortization, and is a measure of the business\'s profitability that excludes these expenses.',
    },
    {
      question: 'What is a Balance Sheet?',
      answer: 'A Balance Sheet is a financial statement that shows the business\'s assets, liabilities, and equity at a specific point in time.',
    },
    {
      question: 'What is a Cash Flow Statement?',
      answer: 'A Cash Flow Statement is a financial statement that shows the business\'s cash inflows and outflows over a specific period of time.',
    },
    {
      question: 'What is Gross Profit?',
      answer: 'Gross Profit is the revenue a company generates minus the cost of goods sold. It is a measure of the profitability of a company core business operations before accounting for expenses such as salaries, rent, and taxes.',
    },
    {
      question: 'What is Net Profit?',
      answer: 'Net Profit is the amount of money a company has left over after deducting all expenses from its revenue. It is a key measure of a company profitability and is often used to evaluate its financial performance.',
    },
    {
      question: 'What is Total Revenue?',
      answer: 'Total Revenue is the total amount of money a company generates from sales of its products or services over a given period of time. It is a key measure of a company financial performance and is often used to evaluate its growth potential.',
    },
    {
      question: 'What is Total Expense?',
      answer: 'Total Expense is the total amount of money a company spends on its operations and other costs over a given period of time. It includes expenses such as salaries, rent, utilities, and other operating expenses.',
    },
    {
      question: 'What is Accounts Receivable?',
      answer: 'Accounts Receivable is the amount of money that a company is owed by its customers for goods or services that have been sold but not yet paid for. It is an important measure of a company liquidity and is often used to evaluate its financial health.',
    },
    {
      question: 'What is Accounts Payable?',
      answer: 'Accounts Payable is the amount of money that a company owes to its suppliers for goods or services that have been received but not yet paid for. It is an important measure of a company liquidity and is often used to evaluate its financial health.',
    },
    {
      question: 'What is Payroll?',
      answer: 'Payroll is the total amount of money that a company pays to its employees for a given period of time. It includes wages, salaries, bonuses, and other compensation.',
    },
    {
      question: 'What is Retention?',
      answer: 'Retention is the rate at which a company is able to retain its customers over time. It is an important measure of customer loyalty and is often used to evaluate the effectiveness of a companys marketing and customer service efforts.',
    },
    {
      question: 'What is Inventory?',
      answer: 'Inventory is the total value of the products or goods that a company has on hand and available for sale. It is an important measure of a company liquidity and is often used to evaluate its financial health.',
    },
    {
      question: 'What is ARPU?',
      answer: 'ARPU (Average Revenue Per User) is a key metric used in the telecommunications and subscription-based industries. It represents the average amount of revenue generated by each user or customer over a given period of time.',
    },
  ];

  useEffect(() => {
    const backAction = () => {
      navigation.goBack();
      return true;
    };

    const backHandler = BackHandler.addEventListener('hardwareBackPress', backAction);

    return () => {
      if (backHandler) {
        backHandler.remove();
      }
    };
  }, []);

  const [searchValue, setSearchValue] = useState('');

  const handleFilterPress = () => {
    setSearchValue('');
  }

  const filteredData = questions.filter(entry =>
    entry.question.toString().toLocaleLowerCase().includes(searchValue.toLocaleLowerCase())
  );

  const handleQuestionPress = (index) => {
    if (index === selectedQuestionIndex) {
      LayoutAnimation.configureNext(LayoutAnimation.Presets.easeInEaseOut);
      setSelectedQuestionIndex(-1);
    } else {
      LayoutAnimation.configureNext(LayoutAnimation.Presets.easeInEaseOut);
      setSelectedQuestionIndex(index);
    }
  };

  return (
    <LinearGradient colors={[colors.linear1, colors.linear2]} style={styles1.container}>
      <View style={styles2.topContainer}>
        <View style={styles2.searchContainer}>
          <Icon name="search" size={20} color={colors.background} style={styles2.searchIcon} />
          <TextInput
            style={styles2.textInput}
            placeholder="Search"
            placeholderTextColor={colors.background}
            onChangeText={(value) => setSearchValue(value)}
            value={searchValue}
          />
        </View>
        <TouchableOpacity style={styles2.filterButton} onPress={handleFilterPress}>
          <Icon name="filter" size={20} color={colors.background} />
        </TouchableOpacity>
      </View>

      <ScrollView showsVerticalScrollIndicator={false}>
        {filteredData.map((item, index) => (
          <React.Fragment key={index}>
            <TouchableOpacity
              style={[styles.questionContainer, selectedQuestionIndex === index && {
                borderBottomLeftRadius: 0,
                borderBottomRightRadius: 0,
              }]}
              onPress={() => handleQuestionPress(index)}
            >
              <Text style={styles.questionText}>{item.question}</Text>
              <Ionicons
                name={selectedQuestionIndex === index ? 'ios-remove-circle' : 'ios-add-circle'}
                size={24}
                color={colors.plusButton}
              />
            </TouchableOpacity>
            {selectedQuestionIndex === index && (
              <Text key={`${index}_answer`} style={styles.answerText}>
                {item.answer}
              </Text>
            )}
          </React.Fragment>
        ))}
        <View style={{marginBottom:'50%'}}></View>
      </ScrollView>

    </LinearGradient>
  );

};

export default FaqScreen;